[package]
name = "hello_macro_derive"
version = "0.1.0"
authors = ["Majedul Hoque <rumanbsl@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version = "0.15.33", features = ["full"]}
quote = "0.6"
